### ISSUE TITLE
Simple Class is not parsed by the PeopleCode grammar

### ISSUE THREAD

**Issue by rojaster** [OpenPplSoft/OPS#3]
Good day,
i'm working on a little pet project where i used yours variant of PeopleCode ANTLR4 grammar. I have some access to real PeopleSoft system and try ti test grammar on it. Those tests is not passing right,look:

<pre>
import PS_PT:Integration:IRequestHandler;
import EOTF_CORE:DVM:MapData;
import EOTF_CORE:Common:*;
import EOTF_CORE:Exceptions:eotfException;

class dvmLookupValue implements PS_PT:Integration:IRequestHandler
   method dvmLookupValue();
   method OnRequest(&_MSG As Message) Returns Message;
   method OnError(&_MSG As Message) Returns string;

private
   Constant &strNSRequest = "http://xmlns.oracle.com/Enterprise/tools/schema/dvmLookupValue.v1";
   Constant &strNSResponse = "http://xmlns.oracle.com/Enterprise/tools/schema/dvmResponse.v1";
end-class;

method dvmLookupValue
end-method;

method OnError
   /+ &_MSG as Message +/
   /+ Returns String +/
   /+ Extends/implements PS_PT:Integration:IRequestHandler.OnError +/

   Return &_MSG.IBException.ToString( True);
end-method;
</pre>

Simple class with two methods, all rules grammar has, but : 
<pre>
line 8:20 token recognition error at: '&_'
line 9:18 token recognition error at: '&_'
line 24:10 token recognition error at: '&_'
line 6:21 no viable alternative at input 'classdvmLookupValueimplements'
</pre> 

And what trace shows:
<pre>
line 8:20 token recognition error at: '&_'
line 9:18 token recognition error at: '&_'
line 24:10 token recognition error at: '&_'
enter   program, LT(1)=import
enter   stmtList, LT(1)=import
enter   stmt, LT(1)=import
enter   appClassImport, LT(1)=import
consume [@0,0:5='import',<30>,1:0] rule appClassImport
enter   appClassPath, LT(1)=PS_PT
consume [@1,7:11='PS_PT',<79>,1:7] rule appClassPath
consume [@2,12:12=':',<31>,1:12] rule appClassPath
consume [@3,13:23='Integration',<79>,1:13] rule appClassPath
consume [@4,24:24=':',<31>,1:24] rule appClassPath
consume [@5,25:39='IRequestHandler',<79>,1:25] rule appClassPath
exit    appClassPath, LT(1)=;
exit    appClassImport, LT(1)=;
exit    stmt, LT(1)=;
consume [@6,40:40=';',<1>,1:40] rule stmtList
enter   stmt, LT(1)=import
enter   appClassImport, LT(1)=import
consume [@7,42:47='import',<30>,2:0] rule appClassImport
enter   appClassPath, LT(1)=EOTF_CORE
consume [@8,49:57='EOTF_CORE',<79>,2:7] rule appClassPath
consume [@9,58:58=':',<31>,2:16] rule appClassPath
consume [@10,59:61='DVM',<79>,2:17] rule appClassPath
consume [@11,62:62=':',<31>,2:20] rule appClassPath
consume [@12,63:69='MapData',<79>,2:21] rule appClassPath
exit    appClassPath, LT(1)=;
exit    appClassImport, LT(1)=;
exit    stmt, LT(1)=;
consume [@13,70:70=';',<1>,2:28] rule stmtList
enter   stmt, LT(1)=import
enter   appClassImport, LT(1)=import
consume [@14,72:77='import',<30>,3:0] rule appClassImport
enter   appPkgPath, LT(1)=EOTF_CORE
consume [@15,79:87='EOTF_CORE',<79>,3:7] rule appPkgPath
consume [@16,88:88=':',<31>,3:16] rule appPkgPath
consume [@17,89:94='Common',<79>,3:17] rule appPkgPath
consume [@18,95:95=':',<31>,3:23] rule appPkgPath
consume [@19,96:96='*',<17>,3:24] rule appPkgPath
exit    appPkgPath, LT(1)=;
exit    appClassImport, LT(1)=;
exit    stmt, LT(1)=;
consume [@20,97:97=';',<1>,3:25] rule stmtList
enter   stmt, LT(1)=import
enter   appClassImport, LT(1)=import
consume [@21,99:104='import',<30>,4:0] rule appClassImport
enter   appClassPath, LT(1)=EOTF_CORE
consume [@22,106:114='EOTF_CORE',<79>,4:7] rule appClassPath
consume [@23,115:115=':',<31>,4:16] rule appClassPath
consume [@24,116:125='Exceptions',<79>,4:17] rule appClassPath
consume [@25,126:126=':',<31>,4:27] rule appClassPath
consume [@26,127:139='eotfException',<79>,4:28] rule appClassPath
exit    appClassPath, LT(1)=;
exit    appClassImport, LT(1)=;
exit    stmt, LT(1)=;
consume [@27,140:140=';',<1>,4:41] rule stmtList
line 6:21 no viable alternative at input 'classdvmLookupValueimplements'
exit    stmtList, LT(1)=<EOF>
exit    program, LT(1)=<EOF>

</pre> 

After 'classdvmLookupValueimplements'  unrecognition, parser stops.

I will continue try to localize a problem and post a solution if i find it

**Comment by rojaster** [comment]
i have my own grammar based on peoplecode syntax reference by oracle - http://docs.oracle.com/cd/E55243_01/pt854pbr0/eng/pt/tpcr/task_PeopleCodeSyntaxQuickReference-c075e8.html#topofpage - but it has some issues too, but do not has issues  like this

**Comment by soorajsasi** [comment]
It looks like the issue is with my definition of the GENERIC_ID rule:

GENERIC_ID : [a-zA-Z] [0-9a-zA-Z_#]* ;

As written, it does not permit underscores in the first character of the generic ID. By modifying it to:

GENERIC_ID : [a-zA-Z_] [0-9a-zA-Z_#]* ;

Your class definition should be parsed successfully.

**Comment by mquinn** [comment]
It looks like the issue is with my definition of the GENERIC_ID rule:

GENERIC_ID : [a-zA-Z] [0-9a-zA-Z_#]* ;

As written, it does not permit underscores in the first character of the generic ID. By modifying it to:

GENERIC_ID : [a-zA-Z_] [0-9a-zA-Z_#]* ;

Your class definition should be parsed successfully.

**Comment by rojaster** [comment]
Nope, i've copied grammar again and added '_'. After tested again :
<pre>
line 8:20 token recognition error at: '&_'
line 9:18 token recognition error at: '&_'
line 24:10 token recognition error at: '&_'
</pre>
there were resolved , but one issue : 
<pre>
line 6:21 no viable alternative at input 'classdvmLookupValueimplements'
</pre>

Look on trace :
<pre>
 grun PeopleCode program -trace < ../tests/small_PS_class_test 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
enter   program, LT(1)=import
enter   stmtList, LT(1)=import
enter   stmt, LT(1)=import
enter   appClassImport, LT(1)=import
consume [@0,0:5='import',<30>,1:0] rule appClassImport
enter   appClassPath, LT(1)=PS_PT
consume [@1,7:11='PS_PT',<79>,1:7] rule appClassPath
consume [@2,12:12=':',<31>,1:12] rule appClassPath
consume [@3,13:23='Integration',<79>,1:13] rule appClassPath
consume [@4,24:24=':',<31>,1:24] rule appClassPath
consume [@5,25:39='IRequestHandler',<79>,1:25] rule appClassPath
exit    appClassPath, LT(1)=;
exit    appClassImport, LT(1)=;
exit    stmt, LT(1)=;
consume [@6,40:40=';',<1>,1:40] rule stmtList
enter   stmt, LT(1)=import
enter   appClassImport, LT(1)=import
consume [@7,42:47='import',<30>,2:0] rule appClassImport
enter   appClassPath, LT(1)=EOTF_CORE
consume [@8,49:57='EOTF_CORE',<79>,2:7] rule appClassPath
consume [@9,58:58=':',<31>,2:16] rule appClassPath
consume [@10,59:61='DVM',<79>,2:17] rule appClassPath
consume [@11,62:62=':',<31>,2:20] rule appClassPath
consume [@12,63:69='MapData',<79>,2:21] rule appClassPath
exit    appClassPath, LT(1)=;
exit    appClassImport, LT(1)=;
exit    stmt, LT(1)=;
consume [@13,70:70=';',<1>,2:28] rule stmtList
enter   stmt, LT(1)=import
enter   appClassImport, LT(1)=import
consume [@14,72:77='import',<30>,3:0] rule appClassImport
enter   appPkgPath, LT(1)=EOTF_CORE
consume [@15,79:87='EOTF_CORE',<79>,3:7] rule appPkgPath
consume [@16,88:88=':',<31>,3:16] rule appPkgPath
consume [@17,89:94='Common',<79>,3:17] rule appPkgPath
consume [@18,95:95=':',<31>,3:23] rule appPkgPath
consume [@19,96:96='*',<17>,3:24] rule appPkgPath
exit    appPkgPath, LT(1)=;
exit    appClassImport, LT(1)=;
exit    stmt, LT(1)=;
consume [@20,97:97=';',<1>,3:25] rule stmtList
enter   stmt, LT(1)=import
enter   appClassImport, LT(1)=import
consume [@21,99:104='import',<30>,4:0] rule appClassImport
enter   appClassPath, LT(1)=EOTF_CORE
consume [@22,106:114='EOTF_CORE',<79>,4:7] rule appClassPath
consume [@23,115:115=':',<31>,4:16] rule appClassPath
consume [@24,116:125='Exceptions',<79>,4:17] rule appClassPath
consume [@25,126:126=':',<31>,4:27] rule appClassPath
consume [@26,127:139='eotfException',<79>,4:28] rule appClassPath
exit    appClassPath, LT(1)=;
exit    appClassImport, LT(1)=;
exit    stmt, LT(1)=;
consume [@27,140:140=';',<1>,4:41] rule stmtList
line 6:21 no viable alternative at input 'classdvmLookupValueimplements'
exit    stmtList, LT(1)=<EOF>
exit    program, LT(1)=<EOF>
</pre>

Same test for two cases and i can't understand why after  issue  it produces next token as EOF

**Comment by soorajsasi** [comment]
Your second issue is due to lack of support in the grammer for classes with an 'implements' clause. Changing the classDeclaration rule from:

classDeclaration : 'class' GENERIC_ID classBlock* 'end-class' ;

to:

classDeclaration : 'class' GENERIC_ID ('implements' appClassPath)? classBlock* 'end-class' ;

should resolve the *line 6:21 no viable alternative at input 'classdvmLookupValueimplements'* error.

This grammar was developed for use mainly on Component/Record/Page PC, which is why you are running into the limitations that you are currently. Even with the two modifications I've listed in this issue, I'm sure there are a few more needed to bring it fully inline with the 8.54 specification, at least as far as app classes are concerned.

**Comment by mquinn** [comment]
Your second issue is due to lack of support in the grammer for classes with an 'implements' clause. Changing the classDeclaration rule from:

classDeclaration : 'class' GENERIC_ID classBlock* 'end-class' ;

to:

classDeclaration : 'class' GENERIC_ID ('implements' appClassPath)? classBlock* 'end-class' ;

should resolve the line 6:21 no viable alternative at input 'classdvmLookupValueimplements' error.

This grammar was developed for use mainly on Component/Record/Page PC, which is why you are running into the limitations that you are currently. Even with the two modifications I've listed in this issue, I'm sure there are a few more needed to bring it fully inline with the 8.54 specification, at least as far as app classes are concerned.

**Comment by rojaster** [comment]
ok, thanks for help and explanation, continue developing my own version
